[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "2cf3c0a3c9b969cf0c1e898549a8bc8f8182f165"
os = "macos"

    [[aws_c_mqtt.download]]
    sha256 = "95121af922941534320a541b8b486430c43bc56771531a4d39efc4364b388c66"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.aarch64-apple-darwin.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "882c9b86ceb373198447422d1de4811de6b5f6d8"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "db6c24095434740a1f12876d8946ce774364ba1c3c22277101953bb5184502fc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.aarch64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "d292682d791628ba78381aaf5d0a4d2489b58abe"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "887939ea7fcd0830a4c935843e9203e4286894f3e52eeccf571517b05b83583b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.aarch64-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "0b519a4bcd7444af65e125ac41a190927730db19"
os = "freebsd"

    [[aws_c_mqtt.download]]
    sha256 = "0cd0b159d9534bc722eb04635bd37296fcd516ebe6c4d93813c2d39826d4f1d4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.aarch64-unknown-freebsd.tar.gz"
[[aws_c_mqtt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dec84fbdeadbd20d2e4a6a2a3988841d29a8f92f"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "8b662b7af62db4d11dc8f2e4f95599a8443e1c1208604564e4de161364db656b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97f59decf009054e74588b6fd6e6fa8177d96fb0"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "48a46a90329777edd565dfe04151bc6e0bf4d6927651737d358c2dc6ef0cfd8a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.armv6l-linux-musleabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b895112e5350803abcbdea3844d6f30b092f1e9"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "5b05fcb5071acee612437bd589ae225b540a601c71dfc64bde1d6942010898b7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3cbbaa1658a50e90a22a55683b64be965adfdcc9"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "41a9eefe2851455bb066bd2d4b9d1166924df09d94740f870f2a66ddd9f71e9f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.armv7l-linux-musleabihf.tar.gz"
[[aws_c_mqtt]]
arch = "i686"
git-tree-sha1 = "9520c69ccdd64a8850d0f3b7fa892c4c9bfc2595"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "df3efb32772df7888fa1a9ca8499652653fdd2112934eda5eae436141fc0e136"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.i686-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "i686"
git-tree-sha1 = "4ec448feabcb86c895644f48d2ff7b3d7adda7a7"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "bbc1f4b00951211c02604b73b710d83dcbdd4b7990ab10fedc5380fd4a529907"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.i686-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "powerpc64le"
git-tree-sha1 = "718e53fc302ddc3ae7f3fa0b187a6866700b81fa"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "78fe0a60e9b7be76ba3bccc7e57aa15c862aafd0fd53e76d55c54e8ca30efb32"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.powerpc64le-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "riscv64"
git-tree-sha1 = "9371f4074e9114e0011f18ebbc5db86207457b4c"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "d7bd8b1fa6b0bf3d7e0e8ae03ad737fd0f689d66304c4ea0e5a8047aa4a50cd0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.riscv64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "26bad95486e986aacfd2dbc7e9faa77413635da4"
os = "macos"

    [[aws_c_mqtt.download]]
    sha256 = "b45d212507ee1526a73a43774b0432c922db7505f12b3ec0453881f8bd24fb27"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.x86_64-apple-darwin.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "05ef6f7bd9d1de34224a78dffb3789e312f8a37c"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "e944c7ad0528d3fdc551c88ba31bad20100a11a70250ed3c0b9da1eb3f6a53d2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.x86_64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "7ef397b6552c51a26d59990ae535dd2bcf8e3066"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "a032ca59b66247d61aef853a4eb13e5b2b51210f434eb78a07c8a67975d4e974"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.x86_64-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "f53e7e31b3300a394f1904e95c7fa3d2827b566c"
os = "freebsd"

    [[aws_c_mqtt.download]]
    sha256 = "1f85d91501842141b232d9661530877fe46e847b4ca39c263a35e8406e07752b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.x86_64-unknown-freebsd.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "731ce586d7c309c72079404c9438c411a2839f9b"
os = "windows"

    [[aws_c_mqtt.download]]
    sha256 = "10d2af82ca3b96474f8a6c70021d94122756c2927a44f1d09ceeb2184fa60ee7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.15.1+0/aws_c_mqtt.v0.15.1.x86_64-w64-mingw32.tar.gz"
