# Autogenerated wrapper script for aws_c_mqtt_jll for x86_64-unknown-freebsd
export libaws_c_mqtt

JLLWrappers.@generate_wrapper_header("aws_c_mqtt")
JLLWrappers.@declare_file_product(libaws_c_mqtt)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libaws_c_mqtt,
        "lib/libaws-c-mqtt.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
